### ISSUE TITLE
highlighting from hjson/try shows odd result

### ISSUE THREAD

**Issue by dropwhile** [hjson/vim-hjson#1]
From the /try example on hjson.org, there is one section of output that looks odd in vim-hjson.

```
{
  # commas are optional
  commas:
  {
    one: 1
    two: 2
  }
}
```

Looks like this: 
![20170427-c15nw4zsud](https://cloud.githubusercontent.com/assets/59039/25511944/33e747fa-2b7f-11e7-9b33-46c65bc33601.png)

The `one: 1` part shows the number without highlighting. My vimrc has this in it:
```
hi clear Identifier
hi clear Statement
``` 
But that doesn't seem to explain `1` lacking highlighting.

**Comment by laktak** [comment]
Please check if this works better.

**Comment by dropwhile** [comment]
fixed! Thanks @laktak 👍
