### ISSUE TITLE
Image URLs inside strings treated as comments

### ISSUE THREAD

**Issue by shabbyrobe** [hjson/vim-hjson#2]
Highlighting is broken when strings contain the characters `//`:

![screenshot_2017-11-08_17-00-37](https://user-images.githubusercontent.com/288426/32533762-6704a45a-c4a6-11e7-9428-ee72074f3106.png)

The highlight chosen at the start of the domain name is:

    hi<hjsonLineComment> trans<hjsonLineComment> lo<Comment>

**Comment by laktak** [comment]
I was not able to reproduce your issue (vim 8) but I updated the syntax with the latest specs. Please try with the update.

**Comment by shabbyrobe** [comment]
Thanks for the quick response! I'm using vim 8.0.1238.

Commenting appears to be fixed with the update but string highlighting is now not resolving to Label. I hacked it temporarily by adding `hi def link hjsonKeywordQ         Label`, but unfortunately I am not experienced enough with the baroque nightmare of vim syntax highlighting to offer a real solution.

**Comment by laktak** [comment]
OK, I think I got most of the Hjson testcases working - please try the update.
